### ISSUE TITLE
Scan crashes due to a concurrent map access in FileSystemSourceProvider.checkConditions

### ISSUE THREAD

**Issue by karaziox** [Checkmarx/kics#5412]
### Expected Behavior

Issue happen on the same repo around 30-40% of the time. When the issue doesn't happen, it correctly scans the repository which contains two Dockerfiles and one helm chart and a bunch of go code. It raises a few warnings related to our charts that we haven't addressed yet. Sample summary:
> Files scanned: 15
Parsed files: 11
Queries loaded: 1169
Queries failed to execute: 0

### Actual Behavior

The scanner crashes with a `concurrent map read and map write` panic

```
fatal error: concurrent map read and map write
goroutine 56 [running]:
2022-05-26T18:45:36.2875427Z runtime.throw({0x7a24264?, 0xc0000be500?})
2022-05-26T18:45:36.2875895Z 	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0010ef890 sp=0xc0010ef860 pc=0x4387f1
2022-05-26T18:45:36.2876405Z runtime.mapaccess2_faststr(0x71692a0?, 0xc001c8d350?, {0xc0015516f6, 0xe})
2022-05-26T18:45:36.2881844Z 	/usr/local/go/src/runtime/map_faststr.go:117 +0x3d4 fp=0xc0010ef8f8 sp=0xc0010ef890 pc=0x4135f4
2022-05-26T18:45:36.2891746Z github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).checkConditions(0xc0014d5d40, {0x878e968, 0xc00112b930}, 0x2?, {0xc0015516e0, 0x24}, 0x1)
2022-05-26T18:45:36.2892474Z 	/app/pkg/engine/provider/filesystem.go:207 +0xff fp=0xc0010ef980 sp=0xc0010ef8f8 pc=0x626b95f
2022-05-26T18:45:36.2893133Z github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir.func1({0xc0015516e0, 0x24}, {0x878e968, 0xc00112b930}, {0x0?, 0x0?})
```
[2022-05-27-KicsLogs-MapConcurrentCrash.txt](https://github.com/Checkmarx/kics/files/8786115/2022-05-27-KicsLogs-MapConcurrentCrash.txt)

### Steps to Reproduce the Problem

Here is our full command line. The repository it is run against is private and I'm not quite sure what is the trigger for this issue. It sounds like it would be related to the files more than their content but I'm not familiar with the codebase.
```
docker run -v /home/vsts/work/1/s:/src checkmarx/kics scan -p /src -o /src/ --report-formats json --exclude-queries b03a748a-542d-44f4-bb86-9199ab4fd2d5,2a153952-2544-4687-bcc9-cc8fea814a9b,59312e8a-a64e-41e7-a252-618533dd1ea8,3ca03a61-3249-4c16-8427-6f8e47dda729,8a301064-c291-4b20-adcb-403fe7fd95fd --type Dockerfile,GRPC,Kubernetes,OpenAPI,Terraform --ignore-on-exit results
```

### Specifications
(N/A if not applicable)

-   Version: docker image latest `sha256:f6d5fd396373cf7ed65ceec6333c75c3cbdc58ba30597f84017bf3b34859ad7c`
-   Platform: Linux, `ubuntu-latest` build machine on Azure Devops
-   Subsystem: N/A

**Comment by joaorufi** [comment]
Hi @karaziox, thanks for the issue!

Could you provide us the sample that you are running kics ? If it's a sensitive content, you can send via our private email kics@checkmarx.com

**Comment by joaorufi** [comment]
Since no samples have been provided so far, this linked PR introduces some mutex locks on concurrent read and writes inside `FileSystemSourceProvider`
