### ISSUE TITLE
Conditional tf resources in aws_iam_policy_document causes panic (> v1.6.1)

### ISSUE THREAD

**Issue by alaidler2** [Checkmarx/kics#5932]
### Actual Behavior

When running a scan against a project that contains a conditional resource reference within an `aws_iam_policy_document` block - I'm seeing the following error from v1.6.1 onwards:

```
panic: not a string

goroutine 36 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x2a4a4d8?, 0xc00068a15c?}}, {0x242e260?, 0xc0008e36e0?}})
        /go/pkg/mod/github.com/zclconf/go-cty@v1.11.0/cty/value_ops.go:1259 +0x138
github.com/Checkmarx/kics/pkg/builder/engine.(*Engine).ExpToString(0xc000e27398?, {0x2a4bde0?, 0xc00058d200?})
        /app/pkg/builder/engine/engine.go:175 +0x398
github.com/Checkmarx/kics/pkg/builder/engine.(*Engine).buildString(0x34?, {0xc00044eda0?, 0x2, 0xc000818fe0?})
        /app/pkg/builder/engine/engine.go:188 +0xbb
github.com/Checkmarx/kics/pkg/builder/engine.(*Engine).ExpToString(0x400?, {0x2a4be60?, 0xc00058d6e0?})
        /app/pkg/builder/engine/engine.go:156 +0x157
github.com/Checkmarx/kics/pkg/parser/terraform.resolveTuple({0x2a4bf20?, 0xc0008f50e0?})
        /app/pkg/parser/terraform/data_source.go:317 +0xbb
github.com/Checkmarx/kics/pkg/parser/terraform.resolveDataResources(0x223e940?)
        /app/pkg/parser/terraform/data_source.go:308 +0xaf
github.com/Checkmarx/kics/pkg/parser/terraform.parseDataSourceBody(0xc000818fe0?)
        /app/pkg/parser/terraform/data_source.go:234 +0x22c
github.com/Checkmarx/kics/pkg/parser/terraform.getDataSourcePolicy({0xc000818600?, 0x5?})
        /app/pkg/parser/terraform/data_source.go:98 +0x532
github.com/Checkmarx/kics/pkg/parser/terraform.(*Parser).Resolve(0x21d8080?, {0xc0001a61e0, 0x95, 0xa0}, {0xc000818600, 0xf})
        /app/pkg/parser/terraform/terraform.go:42 +0x51
github.com/Checkmarx/kics/pkg/parser.(*Parser).Parse(0xc000c60a20, {0xc000818600, 0xf}, {0xc0001a61e0, 0x95, 0xa0})
        /app/pkg/parser/parser.go:124 +0x13a
github.com/Checkmarx/kics/pkg/kics.(*Service).sink(0xc0005cda40, {0x2a48d00, 0xc000056040}, {0xc000818600, 0xf}, {0x244b132, 0x7}, {0x2a2cec0, 0xc00012e090}, {0xc001100000, ...})
        /app/pkg/kics/sink.go:42 +0x1c7
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources.func1({0x2a48d00, 0xc000056040}, {0xc000818600, 0xf}, {0x2a377f0?, 0xc00012e090})
        /app/pkg/kics/service.go:70 +0x107
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir.func1({0xc000818600, 0xf}, {0x2a4f5c0, 0xc000bd69c0}, {0x0?, 0x0?})
        /app/pkg/engine/provider/filesystem.go:184 +0x53f
path/filepath.walk({0xc000818600, 0xf}, {0x2a4f5c0, 0xc000bd69c0}, 0xc00015be18)
        /usr/local/go/src/path/filepath/path.go:433 +0x123
path/filepath.walk({0xc0007536f9, 0x5}, {0x2a4f5c0, 0xc000bd65b0}, 0xc000e27e18)
        /usr/local/go/src/path/filepath/path.go:457 +0x285
path/filepath.Walk({0xc0007536f9, 0x5}, 0xc0000d1e18)
        /usr/local/go/src/path/filepath/path.go:520 +0x6c
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir(0xc0007536f9?, {0x2a48d00?, 0xc000056040?}, {0xc0007536f9?, 0x0?}, 0x0, 0x18?, 0x7f4a19f79a68?, 0x20?)
        /app/pkg/engine/provider/filesystem.go:146 +0x91
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).GetSources(0xc0009cd640, {0x2a48d00, 0xc000056040}, 0x0?, 0xc0009cd980, 0x0?)
        /app/pkg/engine/provider/filesystem.go:135 +0x1ce
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources(0xc0005cda40, {0x2a48d00, 0xc000056040}, {0x244b132, 0x7}, 0x0?, 0x0?)
        /app/pkg/kics/service.go:66 +0x207
created by github.com/Checkmarx/kics/pkg/scanner.PrepareAndScan
        /app/pkg/scanner/scanner.go:24 +0xe7
```

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  Use the following test code: 
```
main.tf:
## S3 ALB log bucket ##
resource "aws_s3_bucket" "s3_bucket_alb" {
  count         = var.load_balancer_access_logs_enabled ? 1 : 0
  bucket        = "test-alb-log-bucket"
  force_destroy = true

  tags = {
    Name = "test-alb-log-bucket"
  }
}

data "aws_iam_policy_document" "access_log_bucket_policy_alb" {
  count = var.load_balancer_access_logs_enabled ? 1 : 0
  statement {
    sid    = "AWSLogDeliveryAclCheck"
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["delivery.logs.amazonaws.com"]
    }

    actions = ["s3:GetBucketAcl"]

    resources = ["arn:aws:s3:::${aws_s3_bucket.s3_bucket_alb[0].id}"]

  }
  statement {
    sid = "ALBLogPut"

    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::652711504416:root"]
    }

    actions = ["s3:PutObject"]

    resources = ["arn:aws:s3:::${aws_s3_bucket.s3_bucket_alb[0].id}/alb-logs/*"]

  }
}

resource "aws_s3_bucket_policy" "s3_bucket_policy_alb" {
  count  = var.load_balancer_access_logs_enabled ? 1 : 0
  bucket = aws_s3_bucket.s3_bucket_alb[0].id
  policy = data.aws_iam_policy_document.access_log_bucket_policy_alb[0].json
}

inputs.tf:
variable "load_balancer_access_logs_enabled" {
  type        = bool
  default     = true
  description = "Boolean to enable / disable access_logs."
}
```

2.  Run a scan on this directory: `kics scan -p ./ -o ./  --verbose --log-level TRACE` and the error will be returned
3.  If you remove the index in the policy document when referencing the s3 bucket - the scan completes without error

**Comment by rafaela-soares** [comment]
Hello @alaidler2,

Thank you so much for reporting this bug! PR #5939 will fix it 😊
