### ISSUE TITLE
Runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by agmond** [Checkmarx/kics#6520]
When running KICS v1.7.3, I'm getting the following error:
**panic: runtime error: slice bounds out of range [1:0]**

I'm running KICS with the following arguments:
`scan -t CloudFormation -p <my-path> -o <output-path> -f json --config /cloudformation-config.yaml --disable-secrets`

Stack trace:
```
panic: runtime error: slice bounds out of range [1:0]

goroutine 3265 [running]:
github.com/Checkmarx/kics/pkg/resolver/file.findSection({0x2465040, 0xc00b590360}, {0xc00c0b2f26?, 0x25?})
	/app/pkg/resolver/file/file.go:447 +0x1a5
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).resolvePath(0xc0012e1220, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040?, 0xc00b590360?}, {0xc00c0b2600, 0x2d5}, {0xc00aa1c180, 0x25}, ...)
	/app/pkg/resolver/file/file.go:392 +0x6d7
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).walk(0x4?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, {0x23a8ee0?, 0xc00c0ac390?}, {0xc00aa1c180, 0x25}, ...)
	/app/pkg/resolver/file/file.go:80 +0x21d
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).handleMap(0x56ff83?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, 0xc00c04f860, {0xc00aa1c180, 0x25}, 0x0, ...)
	/app/pkg/resolver/file/file.go:99 +0x185
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).walk(0x4?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, {0x2465040?, 0xc00c04f860?}, {0xc00aa1c180, 0x25}, ...)
	/app/pkg/resolver/file/file.go:89 +0x132
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).handleMap(0x4161d0?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, 0xc00c04f830, {0xc00aa1c180, 0x25}, 0x0, ...)
	/app/pkg/resolver/file/file.go:99 +0x185
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).walk(0x4?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, {0x2465040?, 0xc00c04f830?}, {0xc00aa1c180, 0x25}, ...)
	/app/pkg/resolver/file/file.go:89 +0x132
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).handleMap(0x56fb68?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, 0xc00b590360, {0xc00aa1c180, 0x25}, 0x0, ...)
	/app/pkg/resolver/file/file.go:99 +0x185
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).walk(0x232d8e0?, {0xc00bd84000, 0x14535e, 0x146000}, {0x2465040, 0xc00b590360}, {0x2465040?, 0xc00b590360?}, {0xc00aa1c180, 0x25}, ...)
	/app/pkg/resolver/file/file.go:89 +0x132
github.com/Checkmarx/kics/pkg/resolver/file.(*Resolver).Resolve(0xc0012e1220, {0xc00bd84000, 0x14535e, 0x146000}, {0xc00aa1c180, 0x25}, 0xc000050220?, 0xc0012e1268?)
	/app/pkg/resolver/file/file.go:59 +0x1c8
github.com/Checkmarx/kics/pkg/parser/json.(*Parser).Resolve(0xc001068f90, {0xc00bd84000, 0x14535e, 0x146000}, {0xc00aa1c180, 0x25})
	/app/pkg/parser/json/parser.go:23 +0x166
github.com/Checkmarx/kics/pkg/parser.(*Parser).Parse(0xc000dd1950, {0xc00aa1c180, 0x25}, {0xc00bd84000, 0x14535e, 0x146000})
	/app/pkg/parser/parser.go:124 +0x13a
github.com/Checkmarx/kics/pkg/kics.(*Service).sink(0xc0004d21c0, {0x2e349a0, 0xc000128000}, {0xc00aa1c180, 0x25}, {0x27dbdc4, 0x7}, {0x2e17a80, 0xc000624160}, {0xc00135c000, ...})
	/app/pkg/kics/sink.go:44 +0x20e
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources.func1({0x2e349a0, 0xc000128000}, {0xc00aa1c180, 0x25}, {0x2e22cd0?, 0xc000624160})
	/app/pkg/kics/service.go:72 +0x107
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir.func1({0xc00aa1c180, 0x25}, {0x2e3c100, 0xc00aa26270}, {0x0?, 0x0?})
	/app/pkg/engine/provider/filesystem.go:184 +0x539
path/filepath.walk({0xc00aa1c180, 0x25}, {0x2e3c100, 0xc00aa26270}, 0xc0012e1e18)
	/usr/local/go/src/path/filepath/path.go:480 +0x116
path/filepath.walk({0xc00abce4f8, 0x11}, {0x2e3c100, 0xc00a8575f0}, 0xc0012e1e18)
	/usr/local/go/src/path/filepath/path.go:504 +0x26f
path/filepath.walk({0xc0009b2930, 0x9}, {0x2e3c100, 0xc00120fe10}, 0xc0012e1e18)
	/usr/local/go/src/path/filepath/path.go:504 +0x26f
path/filepath.walk({0xc000836130, 0x5}, {0x2e3c100, 0xc00120e1a0}, 0xc0012e1e18)
	/usr/local/go/src/path/filepath/path.go:504 +0x26f
path/filepath.Walk({0xc000836130, 0x5}, 0xc001054e18)
	/usr/local/go/src/path/filepath/path.go:571 +0x6c
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).walkDir(0xc000836130?, {0x2e349a0?, 0xc000128000?}, {0xc000836130?, 0x20?}, 0x0, 0x1c000b12f00?, 0x7fcc02545b18?, 0x7fcc29c045b8?)
	/app/pkg/engine/provider/filesystem.go:146 +0x91
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).GetSources(0xc0004e4000, {0x2e349a0, 0xc000128000}, 0x0?, 0xc0004cc040, 0x0?)
	/app/pkg/engine/provider/filesystem.go:135 +0x1ed
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources(0xc0004d21c0, {0x2e349a0, 0xc000128000}, {0x27dbdc4, 0x7}, 0x0?, 0x0?)
	/app/pkg/kics/service.go:68 +0x207
created by github.com/Checkmarx/kics/pkg/scanner.PrepareAndScan
	/app/pkg/scanner/scanner.go:24 +0xe7
```

**Comment by kaplanlior** [comment]
Thanks @agmond for the report, can you also attach the IaC file so we could reproduce and verify the fix with?

**Comment by agmond** [comment]
Hi @kaplanlior,
I don't have the files under my hands (they belong to my clients and I have no access to them).
However, I can approve that I saw the same error in more than one repo (of different clients).
